- id: '1612357227991'
  alias: Me notifier quand Veggie Ã  soif
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.humidite_de_veggie
    below: '40'
  condition: []
  action:
  - service: notify.mobile_app_iphone_de_dylan
    data:
      message: ğŸŒ± Veggie a trÃ¨s soif
      target: 3ff7d6cf4ed18895abe56a78c74faab4
  mode: single
- id: '1612361376231'
  alias: Me notifier quand le serveur est trop chaud
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.processor_temperature
    above: '60'
  condition: []
  action:
  - service: notify.mobile_app_iphone_de_dylan
    data:
      message: ğŸ”¥ Le serveur home assistant Ã  dÃ©passer les {{ trigger.above }}Â°C
      target: 3ff7d6cf4ed18895abe56a78c74faab4
  mode: single
- id: '1612361574296'
  alias: Me notifier quand le serveur est trop plein
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.disk_use_percent_home
    above: '75'
  condition: []
  action:
  - service: notify.mobile_app_iphone_de_dylan
    data:
      message: ğŸ’¢ Le serveur home assistantest plein Ã  plus de {{ trigger.above }}%
      target: 3ff7d6cf4ed18895abe56a78c74faab4
  mode: single
- id: '1612361574276'
  alias: Nouvelle version de home assistant
  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      from: "off"
      to: "on"
  action:
    - service: notify.notify
      data:
        message: "ğŸ  La version {{ state_attr('binary_sensor.updater', 'newest_version') }} de home assistant est disponible."
        target: 3ff7d6cf4ed18895abe56a78c74faab4
